### ISSUE TITLE
The Future of the Book course

### ISSUE THREAD

**Issue by n3ry7** [adunning/early-lives-charlemagne#1]
Is there a way I could have access to the content of the The Future of the Book course?

I am really interested in the topic of writing books using markdown as source files.

**Comment by adunning** [comment]
The contents are still at <https://github.com/adunning/future-of-the-book> but if you're interested in Markdown for books specifically you might be more interested in <https://bookdown.org>.

**Comment by n3ry7** [comment]
Thanks!
